[package]
name = "aseprite-dmi"
version = "2.0.0-beta.2"
edition = "2024"
repository = "https://github.com/spacestation13/aseprite-dmi"

[lib]
name = "dmi"
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0"
arboard = "3.6"
base64 = "0.23.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
mlua = { version = "0.11.6", features = ["module", "lua54", "serialize"] }
native-dialog = "0.9"
png = "0.18.1"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "native-tls"] }
sanitize-filename = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
thiserror = "2.0"
open = "5.4"
